about/urls.py
from django.conf.urls import url
from . import views


app_name = 'about'

urlpatterns = [

    # start page
    url(r'^$', views.Main.as_view(), name='home'),

]

home/urls.py
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [

    # start page
    url(r'^$', views.Home.as_view(), name='home'),

]

login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [

    # login page
    url('^$', views.Login.as_view(), name='login'),

    # log up page
    url('^registration/$', views.LogUp.as_view(), name='log_up'),

    # log out
    url(r'logout/$', views.LogOut.as_view(), name='logout'),
]

pickachu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    # homepage
    url(r'^', include('home.urls')),

    # login web page
    url(r'^login/', include('login.urls')),

    # info web page
    url(r'^about/', include('about.urls')),

    url(r'^admin/', admin.site.urls),
]

about/models.py
from django.db import models

# Create your models here.

login/forms.py
from django.contrib.auth.models import User
from django import forms


class UserFormLog(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class UserFormRegistration(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

about/views.py
from django.shortcuts import render
from django.views.generic import View


class Main(View):
    template_name = 'about/home.html'

    def get(self, request):

        return render(request, self.template_name)

home/views.py
from django.shortcuts import render
from django.views.generic import View


class Home(View):
    template_name = 'home/home_page.html'

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from . import forms


class Login(View):

    form_class = forms.UserFormLog
    template_name = 'login/login.html'

    def get(self, request):
        form = self.form_class(None)

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        username = form['username'].value()
        password = form['password'].value()

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home:home')
        return redirect('login:login')


class LogUp(View):

    form_class = forms.UserFormRegistration
    template_name = 'login/log_up.html'

    def get(self, request):
        form = self.form_class(None)

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()

            login(request, user)
            return redirect('home:home')
        return redirect('login:log_up')


class LogOut(View):

    @method_decorator(login_required)
    def get(self, request):
        logout(request)
        return redirect('home:home')

templates/about/home.html
{%  extends 'base.html' %}

{% block import %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'about/css/home.css'%}">
{% endblock %}

{% block title %}
    Info KPI
{% endblock %}


{% block body %}

    <div class="container">
        <div class="text-center">
            <img class="img-rounded" src="{% static 'about/images/header.JPG' %}" style="width: 50%">
        </div>

        <div class="media">
            <div class="media-left">
                <img src="{% static 'about/images/kpi_logo.png' %}" class="media-object" style="width:150px">
            </div>
            <div class="media-body">
                <h2>Kyiv polytechnic institute</h2><h4> (since 2016 – National Technical University of Ukraine “Igor Sikorsky Kyiv Polytechnic Institute”) was founded in 1898. Over the period of its existence it has trained 370 thousand of specialists, 60 thousand of which during of the period of Ukrainian independence.</h4>
                <br>
                <br>
            </div>
        </div>

        <p>
            KPI ranks 4% of the best universities of the world according to the international rating QS and Webometrics.
            It annually holds the highest positions among the best higher educational establishments of Ukraine – “Compass” and “TOP-200 Ukraine”.
            According to Google Corporation, it is the most popular higher educational establishment of Ukraine during the last years.
            <br>
            <br>
            Igor Sikorsky Kyiv Polytechnic Institute is one of biggest educational establishments in Europe. It trains 25 thousand of students, postgraduates; doctorates as well as foreign student from neighbouring and far abroad countries. Every sixth student of Kyiv city is obtaining the education in KPI and every 25th professor and associate professor of Ukraine is a fellow worker of KPI, among all technical higher educational establishments of our country, every fifth faculty and chair is the faculty of chair of KPI.
            <br>
            <br>
            University has 19 faculties, 9 educational and scientific institutes, several scientific and research institutes and educational centers. It trains Bachelors, Specialists and Masters, PhD and Doctors of Science. The university has its own publishing house “Polytechnika”. It employs more than 500 professors and over 1300 associate professors.
            <br>
            <br>
            All rooms and laboratories are equipped with modern facilities; new computer network educational technologies are being implemented that enables to provide qualified education that meet requirements of the best foreign universities.
            <br>
            <br>
            Institute building and Igor Sikorsky Kyiv Polytechnic Institute faculties as well as university hostels are scattered over the area of approximately 120 hectares. This is a real city inside the city. The university has its own Center of culture and art, modern sport complex, policlinics, four sports and recreation bases by the Dniper river, at Black Sea and in Carpathians. Its scientific and technical library is one of the best in country.
            <br>
            <br>
            Igor Sikorsky Kyiv Polytechnic Institute is a principal organization of National information network of higher educational establishment and institutes of National Academy of Sciences – URAN that is integrated with European educational network – GEANT. The university has become the initiator of “Center of supercomputer calculations and data” in Ukraine.
            <br>
            <br>
            New developments of Igor Sikorsky Kyiv Polytechnic Institute are awarded with State prize of Ukraine in the field of science and technology. Scientific park “Kyiv polytechnic” plays a significant role in the commercialization of scientific research results and technical developments of the university.
            <br>
            <br>
            Igor Sikorsky Kyiv Polytechnic Institute cooperates with technical universities of dozens of world countries, a lot of international organizations (UNESСO, UNIDO, WIPO, NATO, EDNES, ICSU, CODATA etc) and the most leading corporations and firms (SIEMENS, FESTO, SAMSUNG, INTEL etc), takes part on international educational, scientific projects and programs.
            <br>
            <br>
            Those who are interested in history of science and technology are familiarized with State polytechnic museum of Igor Sikorsky Kyiv Polytechnic Institute being one of the biggest Ukrainian museums of technology and equipment and the biggest university museum of Ukraine.
            <br>
            <br>
            To remember renowned predecessors there is a monument to famous graduates, scientists whose lives were connected with KPI on campus.
        </p>
    </div>

    <div class="slideshow-container">

        <div class="mySlides fade">
          <div class="numbertext">1 / 3</div>
          <img src="{% static 'about/images/1.jpg' %}" style="width:100%">
          <div class="text">Caption One</div>
        </div>

        <div class="mySlides fade">
          <div class="numbertext">2 / 3</div>
          <img src="{% static 'about/images/2.jpeg' %}" style="width:100%">
          <div class="text">Caption Two</div>
        </div>

        <div class="mySlides fade">
          <div class="numbertext">3 / 3</div>
          <img src="{% static 'about/images/5.jpg' %}" style="width:100%">
          <div class="text">Caption Three</div>
        </div>

    </div>

    <div style="text-align:center">
        <span class="dot"></span>
        <span class="dot"></span>
        <span class="dot"></span>
    </div>


    <script>
    var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
    setTimeout(showSlides, 2000); // Change image every 2 seconds
}
    </script>
    <script href="{% static 'about/js/home.js'%}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">

        {% load static %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>


        <link href="{% static 'base.css' %}" rel="stylesheet" type="text/css">

        {% block import %}{% endblock %}

        <title>{% block title %}{% endblock %}</title>

    </head>

    <body>

        <!--NAVBAR MENU-->

        <div class="lg">
            <nav class="navbar navbar-inverse navbar-fixed-top my_navbar">
                <div class="container">
                    <div class="navbar-header">

                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="{% url 'home:home' %}">KPI open social network</a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav navbar-right">

                            <li class="dropdown">
                                <a class="dropdown-toggle font_medium" data-toggle="dropdown" href="#">Service<span class="caret"></span></a>
                                <ul class="dropdown-menu">

                                    <li><a href="#">Newest</a></li>
                                    <li><a href="#">Hot</a></li>

                                </ul>
                            </li>

                            <li>
                                <form class="navbar-form navbar-left">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </li>

                            <li><a class="font_medium" href="{% url 'about:home' %}">About</a></li>

                            {%  if user.is_authenticated %}

                                <li class="dropdown">
                                    <a class="dropdown-toggle font_medium" data-toggle="dropdown" href="#">{{ user.username }}<span class="caret"></span></a>

                                    <ul class="dropdown-menu">
                                      <li><a href="#">Profile</a></li>
                                      <li><a href="#">Create post</a></li>
                                      <li class="divider" style="background-color: rgba(1,0,34,1);"></li>
                                      <li><a href="#">Settings</a></li>
                                      <li><a href="{% url 'login:logout' %}">Log out</a></li>
                                    </ul>

                                  </li>

                            {% else %}

                                <li><a class="font_medium" href="{% url 'login:login' %}"><span class="glyphicon glyphicon-log-in"></span>Log in</a></li>

                            {% endif %}

                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div style="margin-bottom: 70px"></div>


        <!--THE END -->



        {% block body %}{% endblock %}


    </body>

</html>

templates/home/home_page.html
{%  extends 'base.html' %}

{% block import %}

{% endblock %}

{% block title %}
    KPI open social network
{% endblock %}


{% block body %}

    <div class="container">
        <div class="text-center text-info">
            <h2>Here is an amazing advertisement! Really^)</h2>
        </div>
    </div>

        {% if user.is_authenticated %}
        <h1>Hello {{ user.username }}</h1>
    {% endif %}

{% endblock %}

templates/login/log_up.html
{%  extends 'base.html' %}

{% block import %}

{% endblock %}

{% block title %}
    Log up
{% endblock %}


{% block body %}



    <div class="container">

        <div class="text-center">
            <h2>Welcome unknown! Glad to see u!</h2>
        </div>

        <div class="bg-info text-center">
            <div class="container">

                <div class="col-lg-3"></div>
                <div class="col-lg-5">
                    <form class="form-signin" action="" method="post">

                        {% csrf_token %}
                        <h2 class="form-signin-heading">Please sign up</h2>

                        <label for="username" class="sr-only">Username</label>
                        <input type="text" name="username" value="" id="username" class="form-control" placeholder="Username" required="" autofocus="">

                        <label for="email" class="sr-only">Email address</label>
                        <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required="" autofocus="">

                        <div ng-app="myApp" ng-init="ok=false" ng-controller="formCtrl">
                            <label for="password" class="sr-only">Password</label>
                            <input type="password" name="password" value="" id="password" class="form-control" placeholder="Password" required="">

                            <label class="sr-only">Password</label>
                            <input type="password" name="repeat" value="" class="form-control" placeholder="Repeat password" required="">

                            <button ng-disabled="ok" class="btn btn-lg btn-primary" type="submit" value="{{ next }}">Sign up</button>
                        </div>

                        <a class="btn btn-lg btn-danger" href="{% url 'home:home' %}">Cancel</a>

                    </form>
                </div>

            </div>

        </div>

    </div>

<script>
var app = angular.module('myApp', []);
var pass1;
var pass2;

app.controller('formCtrl', function($scope){
    pass1 = document.getElementsByName('password').value;
    pass2 = document.getElementsByName('repeat').value;

    // $scope.ok = pass1 !== pass2;
    $scope.ok = false;
});
</script>

{% endblock %}

templates/login/login.html
{%  extends 'base.html' %}

{% block import %}

{% endblock %}

{% block title %}
    Login
{% endblock %}


{% block body %}
    <div class="container">

        <div class="text-center">
            <h2>Welcome someone. Show me who you are!</h2>
        </div>

        <div class="bg-info">

            <div class="media">
                <div class="media-left">
                    {% load static %}
                    <div class="img-responsive" style="margin-top: 5%; margin-left: 5%">
                        <img src="{% static 'images/default/Human1.png' %}" alt="human" class="media-object" style="width: 120px">
                    </div>
                </div>
                <div class="media-body">

                    <div class="container">

                        <div class="col-lg-5">

                            <form class="form-signin" action="" method="post">
                                {% csrf_token %}
                                <h2 class="form-signin-heading">Please sign in</h2>

                                <label for="username" class="sr-only">Username</label>
                                <input type="text" name="username" value="" id="username" class="form-control" placeholder="Username" required="" autofocus="">

                                <label for="inputPassword" class="sr-only">Password</label>
                                <input type="password" name="password" value="" id="inputPassword" class="form-control" placeholder="Password" required="">

                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" value="remember-me"> Remember me
                                    </label>
                                </div>
                                <button class="btn btn-lg btn-primary" type="submit" value="{{ next }}">Sign in</button>
                                <a href="{% url 'login:log_up' %}">Log up</a>
                            </form>

                        </div>

                    </div>

                </div>
            </div>

        </div>
    </div>
{% endblock %}

templates/navbar_menu.html
<h1>Hello everyone</h1>